using Beskar.CodeGeneration.ContentGenerator.Models;
using Beskar.CodeGeneration.Extensions.Rendering;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.ContentGenerator.Rendering;

public sealed class ContentTypeRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required ContentTypeSpec Spec { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);
      
      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {ContentGenerator.GeneratorName}[{ContentGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         
         
         writer.CloseBody();
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }
}