using Beskar.CodeGeneration.ContentGenerator.Models;
using Beskar.CodeGeneration.ContentGenerator.Models.Fields;
using Beskar.CodeGeneration.Extensions.Common.Archetypes;
using Beskar.CodeGeneration.Extensions.Common.System;
using Beskar.CodeGeneration.Extensions.Models.Symbols.Archetypes;
using Beskar.CodeGeneration.Extensions.Rendering;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.ContentGenerator.Rendering;

public sealed class ContentTypeRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required Dictionary<string, ContentTypeSpec> ContentTypes { get; init; }
   
   public required ContentTypeSpec Spec { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);
      
      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {ContentGenerator.GeneratorName}[{ContentGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         RenderUsings(ref writer);
         writer.WriteNamespace(Spec.NamedType.Symbol.NameSpace);
         
         RenderEntity(ref writer);
         RenderEntityConfiguration(ref writer);
         RenderTranslationEntities(ref writer);
         
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void RenderEntityConfiguration(ref CodeTextWriter writer)
   {
      var namedType = Spec.NamedType;
      writer.WriteLineInterpolated($"{namedType.GetClassStructModifiersString()} {namedType.Symbol.Name}EntityConfiguration : IEntityTypeConfiguration<{namedType.Symbol.Name}Entity>");
      writer.OpenBody();

      writer.WriteLineInterpolated($"public void Configure(EntityTypeBuilder<{namedType.Symbol.Name}Entity> builder)");
      writer.OpenBody();

      var snakeCase = $"{namedType.Symbol.Name}".SnakeCase();
      
      writer.CloseBody();
      
      writer.CloseBody();
      writer.WriteLine();
   }

   private void RenderEntity(ref CodeTextWriter writer)
   {
      var namedType = Spec.NamedType;
      var hasBaseType = false;
      
      writer.WriteLineInterpolated($"{namedType.GetClassStructModifiersString()} {namedType.Symbol.Name}Entity");

      if (Spec.BaseTypeFullName is { } baseTypeFullName 
          && ContentTypes.TryGetValue(baseTypeFullName, out var baseType))
      {
         writer.UpIndent();
         writer.WriteLineInterpolated($": {baseType.NamedType.Symbol.FullName}Entity");
         writer.DownIndent();
         
         hasBaseType = true;
      }
      
      writer.OpenBody();

      if (!hasBaseType)
      {
         writer.WriteLine("public ContentTypeId Id { get; set; }");
         writer.WriteLine();
      }
      
      foreach (var property in Spec.Fields.Array.Where(x => x is not IdFieldSpec))
      {
         if (property.IsLocalized)
         {
            RenderLocalizedField(ref writer, property);
            continue;
         }
         
         if (property is ComponentReferenceSpec component)
         {
            writer.WriteLineInterpolated($"public {component.FullName}Entity? {component.PropertyName} {{ get; set; }}");
         }
         else if (property is ComponentCollectionSpec collection)
         {
            writer.WriteLineInterpolated($"public List<{collection.FullName}Entity> {collection.PropertyName} => field ??= [];");
         }
         else
         {
            var requiredText = property.IsRequired ? "required " : "";
            var nativeName = property.NativePropertyType;
            var nullableText = nativeName == "string" && !property.IsRequired ? "?" : "";
            
            writer.WriteLineInterpolated($"public {requiredText}{nativeName}{nullableText} {property.PropertyName} {{ get; set; }}");
         }
         
         writer.WriteLine();
      }
      
      writer.CloseBody();
      writer.WriteLine();
   }

   private void RenderLocalizedField(ref CodeTextWriter writer, FieldSpec field)
   {
      var namedType = Spec.NamedType;
      var name = $"{namedType.Symbol.Name}{field.PropertyName}Translation";
      
      writer.WriteLineInterpolated($"public List<{name}> {field.PropertyName} => field ??= [];");
      writer.WriteLine();
   }

   private void RenderTranslationEntities(ref CodeTextWriter writer)
   {
      var namedType = Spec.NamedType;
      
      foreach (var property in Spec.Fields.Array.Where(x => x.IsLocalized))
      {
         var name = $"{namedType.Symbol.Name}{property.PropertyName}Translation";
         
         writer.WriteLineInterpolated($"public sealed class {name} : TranslationEntity<{property.NativePropertyType}>");
         writer.OpenBody();

         if (property is ComponentReferenceSpec component)
         {
            writer.WriteLineInterpolated($"public {component.FullName}Entity? Target {{ get; set; }}");
         }
         else if (property is ComponentCollectionSpec collection)
         {
            writer.WriteLineInterpolated($"public {collection.FullName}Entity? Target {{ get; set; }}");
            writer.WriteLine();

            writer.WriteLine("public int SortOrder { get; set; }");
         }
         
         writer.CloseBody();
         writer.WriteLine();

         var snakeName = name.SnakeCase();
         writer.WriteLineInterpolated($"public sealed class {name}Configuration() : TranslationEntityConfiguration<{name}, {property.NativePropertyType}>(\"{snakeName}\")");
         writer.OpenBody();

         writer.WriteLineInterpolated($"public override void Configure(EntityTypeBuilder<{name}> builder)");
         writer.OpenBody();

         writer.WriteLine("base.Configure(builder);");
         writer.WriteLine();

         if (property is ComponentReferenceSpec or ComponentCollectionSpec)
         {
            writer.WriteLine("builder.HasOne(x => x.Target)");
            writer.UpIndent();
            
            writer.WriteLine(".WithMany()");
            writer.WriteLine(".HasForeignKey(x => x.Value)");
            writer.WriteLine(".OnDelete(DeleteBehavior.Restrict);");
            
            writer.DownIndent();
         }
         
         writer.CloseBody();
         
         writer.CloseBody();
         writer.WriteLine();
      }
   }

   private static void RenderUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System");
      writer.WriteUsing("Microsoft.EntityFrameworkCore");
      writer.WriteUsing("Microsoft.EntityFrameworkCore.Metadata.Builders");
      writer.WriteUsing("Beskar.CodeGeneration.ContentGenerator.Marker.Fields");
      writer.WriteUsing("Beskar.CodeGeneration.ContentGenerator.Marker.Templates");
      writer.WriteLine();
   }
}