using Beskar.CodeGeneration.Extensions.Models.Symbols.Archetypes;
using Beskar.CodeGeneration.Extensions.Rendering;
using Beskar.CodeGeneration.LanguageGenerator.Models;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.LanguageGenerator.Rendering;

public sealed class LangGroupRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required LanguageEnumSpec Spec { get; init; }
   
   private string _langGroupName = string.Empty;
   private readonly List<FieldSymbolArchetype> _fields = [];
   
   protected override string Render()
   {
      InitializeFields();
      
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {LanguageGenerator.GeneratorName}[{LanguageGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();

         WriteUsings(ref writer);
         writer.WriteNamespace("Beskar.Languages");
         
         WriteScaffold(ref writer);
         
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteScaffold(ref CodeTextWriter writer)
   {
      writer.WriteLineInterpolated($"public static partial class LangKey");
      writer.OpenBody();
      
      writer.WriteLineInterpolated($"public static partial class {_langGroupName}");
      writer.OpenBody();

      foreach (var field in _fields)
      {
         var attr = (LanguageKeySpec)field.Field.Attributes.Array[0];
         writer.WriteLineInterpolated($"public const string {field.Symbol.Name} = \"{_langGroupName}.{attr.Name}\";");
      }
      
      writer.CloseBody();
      writer.CloseBody();
      writer.WriteLine();
   }

   private void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System");
      writer.WriteLine();
   }

   private void InitializeFields()
   {
      _langGroupName = Spec.GroupName;
      _fields.Clear();
      
      foreach (ref var fieldArchetype in Spec.EnumTypeArchetype.NamedType.Fields)
      {
         if (fieldArchetype.Field.Attributes.Array is not [_])
         {
            continue;
         }
         
         _fields.Add(fieldArchetype);
      }
   }
}