using Beskar.CodeGeneration.Extensions.Rendering;
using Beskar.CodeGeneration.LanguageGenerator.Models;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Beskar.CodeGeneration.LanguageGenerator.Rendering;

public sealed class LangFacadeRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required List<LanguageEnumSpec> Specs { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {LanguageGenerator.GeneratorName}[{LanguageGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();

         WriteUsings(ref writer);
         writer.WriteNamespace("Beskar.Languages");

         writer.WriteLine("public sealed partial class TranslationFacade(ITranslationProvider provider)");
         writer.OpenBody();

         writer.WriteLine("private readonly ITranslationProvider _provider = provider;");

         foreach (var spec in Specs)
         {
            writer.WriteLine();
            writer.WriteLineInterpolated($"public {spec.GroupName}Facade {spec.GroupName} => field ??= new(_provider);");
            writer.WriteLine();
            
            writer.WriteLineInterpolated($"public sealed class {spec.GroupName}Facade(ITranslationProvider p)");
            writer.OpenBody();
            
            writer.WriteLine("private readonly ITranslationProvider _p = p;");
            
            foreach (ref var fieldArchetype in spec.EnumTypeArchetype.NamedType.Fields)
            {
               if (fieldArchetype.Field.Attributes.Array is not [_])
               {
                  continue;
               }
         
               writer.WriteLine();
               writer.WriteLineInterpolated($"public string {fieldArchetype.Symbol.Name} => _p.Get(LangKey.{spec.GroupName}.{fieldArchetype.Symbol.Name});");
            }
            writer.CloseBody();
         }
         
         writer.CloseBody();
         writer.WriteLine();
         
         WriteDefaultValues(ref writer);
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteDefaultValues(ref CodeTextWriter writer)
   {
      writer.WriteLineInterpolated($"public static partial class LangKey");
      writer.OpenBody();

      writer.WriteLineInterpolated($"public static string GetDefaultValue(string fullKey)");
      writer.OpenBody();

      writer.WriteLine("return fullKey switch");
      writer.OpenBody();
      foreach (var spec in Specs)
      {
         foreach (ref var fieldArchetype in spec.EnumTypeArchetype.NamedType.Fields)
         {
            if (fieldArchetype.Field.Attributes.Array is not [LanguageKeySpec attr])
            {
               continue;
            }

            var escapedValue = SymbolDisplay.FormatLiteral(attr.DefaultValue, true);
            writer.WriteLineInterpolated($"LangKey.{spec.GroupName}.{fieldArchetype.Symbol.Name} => {escapedValue},");
         }
      }
      
      writer.WriteLine("_ => fullKey");
      writer.CloseBodySemicolon();
      writer.CloseBody();
      writer.WriteLine();

      writer.WriteLine("public static readonly ImmutableArray<string> AllKeys = ImmutableArray.CreateRange<string>([");
      writer.UpIndent();
      
      foreach (var spec in Specs)
      {
         foreach (ref var fieldArchetype in spec.EnumTypeArchetype.NamedType.Fields)
         {
            if (fieldArchetype.Field.Attributes.Array is not [LanguageKeySpec attr])
            {
               continue;
            }

            writer.WriteLineInterpolated($"LangKey.{spec.GroupName}.{fieldArchetype.Symbol.Name},");
         }
      }
      
      writer.DownIndent();
      writer.WriteLine("]);");
         
      writer.CloseBody();
   }
   
   private void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System.Collections.Immutable");
      writer.WriteUsing("Beskar.CodeGeneration.LanguageGenerator.Marker.Interfaces");
      writer.WriteLine();
   }
}