using System.Collections.Immutable;
using Beskar.CodeGeneration.Extensions.Rendering;
using Beskar.CodeGeneration.LanguageGenerator.Models;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.LanguageGenerator.Rendering;

public sealed class LangFacadeRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required List<LanguageEnumSpec> Specs { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {LanguageGenerator.GeneratorName}[{LanguageGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();

         WriteUsings(ref writer);
         writer.WriteNamespace("Beskar.Languages");

         writer.WriteLine("public sealed partial class TranslationFacade(ITranslationProvider provider)");
         writer.OpenBody();

         writer.WriteLine("private readonly ITranslationProvider _provider = provider;");

         foreach (var spec in Specs)
         {
            writer.WriteLine();
            writer.WriteLineInterpolated($"public {spec.GroupName}Facade {spec.GroupName} => field ??= new(_provider);");
            writer.WriteLine();
            
            writer.WriteLineInterpolated($"public sealed class {spec.GroupName}Facade(ITranslationProvider p)");
            writer.OpenBody();
            
            writer.WriteLine("private readonly ITranslationProvider _p = p;");
            
            foreach (ref var fieldArchetype in spec.EnumTypeArchetype.NamedType.Fields)
            {
               if (fieldArchetype.Field.Attributes.Array is not [_])
               {
                  continue;
               }
         
               writer.WriteLine();
               writer.WriteLineInterpolated($"public string {fieldArchetype.Symbol.Name} => _p.Get(LangKey.{spec.GroupName}.{fieldArchetype.Symbol.Name});");
            }
            writer.CloseBody();
         }
         
         writer.CloseBody();
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }
   
   private void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("Beskar.CodeGeneration.LanguageGenerator.Marker.Interfaces");
      writer.WriteLine();
   }
}