using Beskar.CodeGeneration.Extensions.Rendering;
using Beskar.CodeGeneration.ObserveGenerator.Models;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Beskar.CodeGeneration.ObserveGenerator.Rendering;

public sealed class ObserveRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required ObserveSpec Spec { get; init; }

   private string _className = string.Empty;
   
   protected override string Render()
   {
      InitializeFields();
      
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {ObserveGenerator.GeneratorName}[{ObserveGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         WriteUsings(ref writer);
         writer.WriteNamespace(Spec.NamedTypeArchetype.Symbol.NameSpace);

         WriteClass(ref writer);
         WriteInstrumentation(ref writer);
         
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteClass(ref CodeTextWriter writer)
   {
      
   }
   
   private void WriteInstrumentation(ref CodeTextWriter writer)
   {
      writer.WriteLineInterpolated($"internal static class {_className}Instrumentation");
      writer.OpenBody();

      if (Spec.ActivitySpec is { } activity)
      {
         var activityName = SymbolDisplay.FormatLiteral(activity.Name, true);
         writer.WriteLineInterpolated($"public static readonly ActivitySource = new({activityName}, \"{activity.Version}\");");
      }

      if (Spec.MeterSpec is { } meter)
      {
         var meterName = SymbolDisplay.FormatLiteral(meter.Name, true);
         writer.WriteLineInterpolated($"public static readonly Meter MeterSource = new({meterName}, \"{meter.Version}\");");
      }

      writer.WriteLine();

      foreach (var instrument in Spec.InsrumentSpecs)
      {
         writer.WriteLineInterpolated($"public static readonly Instrument {instrument.Name} = new({instrument.Name});");
      }
      
      writer.CloseBody();
   }

   private (string Type, string Method) GetInstrumentationNames(ObserveInstrumentSpec spec)
   {
      return spec.InstrumentFullName switch
      {
         "Beskar.CodeGeneration.ObserveGenerator.Marker.Enums.InstrumentKind.Counter" => ("Counter", "CreateCounter"),
         "Beskar.CodeGeneration.ObserveGenerator.Marker.Enums.InstrumentKind.Gauge" => ("Gauge", "CreateGauge"),
         "Beskar.CodeGeneration.ObserveGenerator.Marker.Enums.InstrumentKind.Histogram" => ("Histogram", "CreateHistogram"),
         "Beskar.CodeGeneration.ObserveGenerator.Marker.Enums.InstrumentKind.UpDownCounter" => ("UpDownCounter", "CreateUpDownCounter"),
         _ => throw new InvalidOperationException($"Unknown instrument kind: {spec.InstrumentFullName}")
      };
   }
   
   private void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System");
      writer.WriteUsing("System.Diagnostics");
      writer.WriteUsing("System.Diagnostics.Metrics");
      writer.WriteLine();
   }

   private void InitializeFields()
   {
      _className = Spec.NamedTypeArchetype.Symbol.Name;
   }
}