using Beskar.CodeGeneration.Extensions.Common.Archetypes;
using Beskar.CodeGeneration.Extensions.Rendering;
using Beskar.CodeGeneration.ProcessorGenerator.Enums;
using Beskar.CodeGeneration.ProcessorGenerator.Models;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.ProcessorGenerator.Rendering;

public sealed class PipelineRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required ProcessorPipelineSpec Spec { get; init; }

   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);
      
      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {ProcessorGenerator.GeneratorName}[{ProcessorGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         WriteUsings(ref writer);
         writer.WriteNamespace(Spec.Archetype.Symbol.NameSpace);

         var arch = Spec.Archetype;
         writer.WriteLineInterpolated($"{arch.GetClassStructModifiersString(true)} {arch.Symbol.Name}");
         writer.OpenBody();

         WriteGetFactory(ref writer);
         WriteExecute(ref writer);
         WriteContext(ref writer);
         
         writer.CloseBody();
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteContext(ref CodeTextWriter writer)
   {
      writer.WriteLineInterpolated($"public sealed class {Spec.Archetype.Symbol.Name}Context : ProcessorContext");
      writer.OpenBody();

      foreach (var variable in Spec.ContextVariables)
      {
         writer.WriteLineInterpolated($"public {variable.TypeFullName}{(variable.IsReferenceType ? "?" : "")} {variable.Name} {{ get; set; }}");
         writer.WriteLine();
      }
      
      writer.CloseBody();
   }
   
   private void WriteGetFactory(ref CodeTextWriter writer)
   {
      var arch = Spec.Archetype;

      writer.WriteLineInterpolated($"public static {arch.Symbol.FullName} GetFactory(IServiceProvider provider)");
      writer.OpenBody();

      writer.WriteLineInterpolated($"var pipeline = new {arch.Symbol.FullName}()");
      writer.OpenBody();

      foreach (var processor in Spec.ProcessorRegisters)
      {
         writer.WriteLineInterpolated($"{processor.PropertyName} = provider.GetService(typeof({processor.FullTypeName})) as {processor.FullTypeName}");
         writer.UpIndent();
         writer.WriteLineInterpolated($"?? throw new InvalidOperationException(\"Cannot resolve {processor.FullTypeName}\"),");
         writer.DownIndent();
      }
      
      writer.CloseBodySemicolon();
      writer.WriteLine();

      foreach (var processor in Spec.ProcessorRegisters.Array.Where(x => x.Settings.Array.Length > 0))
      {
         foreach (var setting in processor.Settings)
         {
            writer.WriteLineInterpolated($"pipeline.{processor.PropertyName}.{setting.PropertyName} = {setting.ValueFullExpression};");
         }
         
         writer.WriteLine();
      }
      
      writer.WriteLine("return pipeline;");
      writer.CloseBody();
      writer.WriteLine();
   }

   private void WriteExecute(ref CodeTextWriter writer)
   {
      var isAllSync = Spec.ProcessorRegisters.Array.All(x => x.ExecuteKind is ProcessorKind.Sync && x.PostKind is null or ProcessorKind.Sync);
      var orderedProcessors = Spec.ProcessorRegisters.Array.OrderBy(x => x.StepSpec.Order).ToArray();
      
      var firstProcessor = orderedProcessors[0];
      var lastProcessor = orderedProcessors[^1];
      
      if (isAllSync)
      {
         writer.WriteInterpolated($"public Result<{lastProcessor.OutputFullTypeName}, ProcessorError>");
      }
      else
      {
         writer.WriteInterpolated($"public async Task<Result<{lastProcessor.OutputFullTypeName}, ProcessorError>>");
      }
      
      writer.WriteLineInterpolated($" Execute({firstProcessor.InputFullTypeName} input, CancellationToken ct)");
      writer.OpenBody();
      
      writer.WriteLineInterpolated($"ProcessorContext context = new {Spec.Archetype.Symbol.Name}Context()");
      writer.OpenBody();
      writer.WriteLineInterpolated($"PipelineName = \"{Spec.Name}\"");
      writer.CloseBodySemicolon();
      writer.WriteLine();

      if (Spec.TimeoutSpec is { } timeout)
      {
         writer.WriteLine("using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);");
         writer.WriteLineInterpolated($"cts.CancelAfter({timeout.Milliseconds});");
         writer.WriteLine("ct = cts.Token;");
         writer.WriteLine();
      }

      var counter = 0;
      foreach (var processor in orderedProcessors)
      {
         counter++;
         
         var inputName = counter == 1 ? "input" : $"r{counter - 1}.Success";
         var asyncName = processor.ExecuteKind is ProcessorKind.Sync ? "" : "await ";
         
         writer.WriteLineInterpolated($"var r{counter} = {asyncName}{processor.PropertyName}.Execute(context, {inputName}, ct);");
         writer.WriteLineInterpolated($"if (!r{counter}.HasValue) return r{counter}.Error;");
         writer.WriteLine();
      }

      var pCounter = 0;
      foreach (var processor in orderedProcessors.Where(x => x.PostKind is not null).Reverse())
      {
         pCounter++;
         var asyncName = processor.PostKind is ProcessorKind.Sync ? "" : "await ";
         
         writer.WriteLineInterpolated($"var error{pCounter} = {asyncName}{processor.PropertyName}.Post(context, ct);");
         writer.WriteLineInterpolated($"if (error{pCounter} is not null) return error{pCounter};");
         writer.WriteLine();
      }
      
      writer.WriteLineInterpolated($"return r{counter}.Success;");
      
      writer.CloseBody();
      writer.WriteLine();
   }

   private void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System");
      writer.WriteUsing("System.Threading");
      writer.WriteUsing("System.Threading.Tasks");
      writer.WriteUsing("Beskar.CodeGeneration.ProcessorGenerator.Marker.Models");
      writer.WriteUsing("Me.Memory.Results");
      writer.WriteLine();
   }
}