using Beskar.CodeGeneration.Extensions.Rendering;
using Beskar.CodeGeneration.TypeIdGenerator.Models;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.TypeIdGenerator.Rendering;

public sealed class TypeIdRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required TypeSafeIdSpec Spec { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);
      
      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"This file is auto-generated by {TypeIdGenerator.GeneratorName}[{TypeIdGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         writer.WriteUsing("System");
         writer.WriteLine();
         
         writer.WriteNamespace(Spec.NamedTargetArchetype.Symbol.NameSpace);
         
         
         
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }
}