using System.Collections.Immutable;
using Beskar.CodeGeneration.Extensions.Rendering;
using Beskar.CodeGeneration.PacketGenerator.Models;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.PacketGenerator.Rendering;

public sealed class PacketRenderer(SourceProductionContext ctx)
   : CodeRenderer(ctx)
{
   public required ImmutableArray<PacketSpec> PacketSpecs { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {PacketGenerator.GeneratorName}[{PacketGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();

         writer.WriteUsing("System.Runtime.CompilerServices");
         writer.WriteUsing("Beskar.CodeGeneration.PacketGenerator.Marker.Models");
         writer.WriteLine();
         
         writer.WriteNamespace("Beskar.PacketGenerator.Packets");

         writer.WriteLineInterpolated($"file static class MetadataInitializer");
         writer.OpenBody();

         writer.WriteLine("[ModuleInitializer]");
         writer.WriteLine("internal static void Initialize()");
         writer.OpenBody();

         var counter = 0;
         foreach (var spec in SortPackets(PacketSpecs))
         {
            writer.WriteLineInterpolated($"PacketMetadata<{spec.NamedTypeArchetype.Symbol.FullName}>.Identifier = {counter++};");
            writer.WriteLine();
         }
         
         writer.CloseBody();
         writer.CloseBody();
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }
   
   private static IEnumerable<PacketSpec> SortPackets(IEnumerable<PacketSpec> packets)
   {
      return packets.OrderBy(x => x.NamedTypeArchetype.Symbol.FullName);
   }
}