using System.Collections.Immutable;
using Beskar.CodeGeneration.Extensions.Rendering;
using Beskar.CodeGeneration.PacketGenerator.Models;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.PacketGenerator.Rendering;

public sealed class PacketRenderer(SourceProductionContext ctx)
   : CodeRenderer(ctx)
{
   public required ImmutableArray<PacketSpec> PacketSpecs { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {PacketGenerator.GeneratorName}[{PacketGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         
         
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }
}