using Beskar.CodeGeneration.EnumGenerator.Models;
using Beskar.CodeGeneration.Extensions.Rendering;
using Me.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.CodeGeneration.EnumGenerator.Rendering;

public sealed class EnumExtensionRenderer(SourceProductionContext ctx)
   : CodeRenderer(ctx)
{
   public required FastEnumSpec Spec { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {EnumGenerator.GeneratorName}[{EnumGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         
         writer.WriteLine();

         
         
         writer.CloseBody();
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }
}